/*
  # Add Affirmation Source Column to Journal Entries

  1. Changes
    - Add affirmation_source column to journal_entries table
  
  2. Reason
    - This column will store whether an affirmation was generated by AI or is a fallback
    - Helps users understand the source of their affirmations
    - Useful for debugging and improving the affirmation generation process
*/

-- Add affirmation_source column to journal_entries table if it doesn't exist
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'journal_entries' AND column_name = 'affirmation_source'
  ) THEN
    ALTER TABLE public.journal_entries ADD COLUMN affirmation_source TEXT;
  END IF;
END $$;

-- Add comment to explain the column
COMMENT ON COLUMN journal_entries.affirmation_source IS 'Source of the affirmation (ai or fallback)';